name: Deploy Web App to Azure

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/html:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/html:latest

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.VM_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Run Ansible Playbook on Azure VM
      run: |
        ansible-playbook -i "${{ secrets.VM_HOST }}," \
          --user ${{ secrets.VM_SSH_USER }} \
          --private-key key.pem \
          ansible/deploy-docker.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
